name: sentiment_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - certifi=2020.6.20=py36hd36e781_2
  - pip=20.2.4=py_0
  - python=3.6.11=h6f26aa1_2_cpython
  - python_abi=3.6=1_cp36m
  - setuptools=49.6.0=py36hd36e781_2
  - vc=14.1=h869be7e_1
  - vs2015_runtime=14.16.27012=h30e32a0_2
  - wheel=0.35.1=pyh9f0ad1d_0
  - wincertstore=0.2=py36h9f0ad1d_1005
  - pip:
    - absl-py==0.11.0
    - astroid==2.4.2
    - astunparse==1.6.3
    - backcall==0.2.0
    - cachetools==4.1.1
    - chardet==3.0.4
    - click==7.1.2
    - colorama==0.4.4
    - decorator==4.4.2
    - flask==1.1.2
    - gast==0.3.3
    - google-auth==1.23.0
    - google-auth-oauthlib==0.4.2
    - google-pasta==0.2.0
    - grpcio==1.33.2
    - h5py==2.10.0
    - idna==2.10
    - importlib-metadata==2.0.0
    - ipykernel==5.3.4
    - ipython==7.16.1
    - ipython-genutils==0.2.0
    - isort==5.6.4
    - itsdangerous==1.1.0
    - jedi==0.17.2
    - jinja2==2.11.2
    - joblib==0.17.0
    - jupyter-client==6.1.7
    - jupyter-core==4.6.3
    - keras-preprocessing==1.1.2
    - lazy-object-proxy==1.4.3
    - lxml==4.6.1
    - markdown==3.3.3
    - markupsafe==1.1.1
    - mccabe==0.6.1
    - nltk==3.5
    - numpy==1.18.5
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - pandas==1.1.4
    - parso==0.7.1
    - pickleshare==0.7.5
    - prompt-toolkit==3.0.8
    - protobuf==3.13.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.7.2
    - pylint==2.6.0
    - python-dateutil==2.8.1
    - pytz==2020.4
    - pywin32==228
    - pyzmq==19.0.2
    - regex==2020.10.28
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - scikit-learn==0.23.2
    - scipy==1.5.3
    - six==1.15.0
    - sklearn==0.0
    - tensorboard==2.3.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.3.1
    - tensorflow-estimator==2.3.0
    - termcolor==1.1.0
    - threadpoolctl==2.1.0
    - toml==0.10.2
    - tornado==6.1
    - tqdm==4.51.0
    - traitlets==4.3.3
    - typed-ast==1.4.1
    - urllib3==1.25.11
    - wcwidth==0.2.5
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - zipp==3.4.0
prefix: C:\Users\nana-\anaconda3\envs\data_engineering

